name: Create and publish docker images

on: push

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        image:
          - gateway

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image name
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          IMAGE_TAG=latest
          echo "DOCKER_IMAGE=${{ secrets.DOCKER_USER }}/${{ matrix['image'] }}:$IMAGE_TAG" >> $GITHUB_ENV
      - name: Build docker image
        run: >-
          docker build ${{ matrix['image'] }}
          --label "org.label-schema.vcs-ref=$GITHUB_SHA"
          --tag $DOCKER_IMAGE
      - run: docker push $DOCKER_IMAGE
